name: Integration Test

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
env:
  TF_VAR_project: ${{ secrets.GCLOUD_PROJECT }}
jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Install Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_version: 1.5.7

      - name: lint
        run: terraform fmt *.tf modules/*/*.tf
        shell: bash
